/*
 * This source file was generated by the Gradle 'init' task
 */
package novzoommeet;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

import novdfsislandleetcode200.app;

class apptest {
    @Test void appHasAGreeting() {
        app classUnderTest = new app();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
