/*
 * This source file was generated by the Gradle 'init' task
 */
package Nov21AttemptRetry;

public class app {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new app().getGreeting());
    }
}
